/**********************
***********************/

   DEF TEMP-TABLE Cariler
      FIELD CariId AS INTEGER
      FIELD CariKod AS CHARACTER FORMAT "X(32)":U 
      FIELD CariAd AS CHARACTER FORMAT "X(127)":U 
      FIELD KisaAd AS CHARACTER FORMAT "X(127)":U 
      FIELD BolgeKod AS CHARACTER FORMAT "X(31)":U 
      FIELD Adres1 AS CHARACTER FORMAT "X(255)":U 
      FIELD Adres2 AS CHARACTER FORMAT "X(255)":U 
      FIELD Adres3 AS CHARACTER FORMAT "X(255)":U 
      FIELD FaturaAdres1 AS CHARACTER FORMAT "X(255)":U 
      FIELD FaturaAdres2 AS CHARACTER FORMAT "X(255)":U 
      FIELD FaturaAdres3 AS CHARACTER FORMAT "X(255)":U 
      FIELD VarigDaire AS CHARACTER FORMAT "X(63)":U 
      FIELD VergiNo AS CHARACTER FORMAT "X(63)":U
      FIELD GrupKod AS CHARACTER FORMAT "X(63)":U. /*cgrup_kod3*/
      
   
DEFINE DATASET CarilerDS FOR Cariler.
DEFINE OUTPUT PARAMETER DATASET FOR CarilerDS.

DEFINE INPUT PARAMETER  xId AS INTEGER.
DEFINE INPUT PARAMETER  xId2 AS INTEGER.

DEFINE INPUT PARAMETER  xKod AS CHARACTER.
DEFINE INPUT PARAMETER  xAd AS CHARACTER.
DEFINE INPUT PARAMETER  xAciklama AS CHAR.
DEFINE INPUT PARAMETER  xKod1 AS CHARACTER.
DEFINE INPUT PARAMETER  xKod2 AS CHARACTER.

DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}

RUN Cariler_run (OUTPUT TABLE Cariler, 
                 INPUT xId, INPUT xId2, INPUT xKod, INPUT xAd, INPUT xAciklama,
                 INPUT xKod1, INPUT xKod2, INPUT Firma, INPUT Limit).
