/*
12.07.2012 ArmaFiltre
Is emrinde kullanilan malzemeleri degistirmek icin
*/

DEFINE INPUT PARAMETER fkod AS CHARACTER.
DEFINE INPUT PARAMETER ukod AS CHARACTER.
DEFINE INPUT PARAMETER IsEmriNo AS CHARACTER.
DEFINE INPUT PARAMETER MalzemeKod AS CHARACTER.
DEFINE INPUT PARAMETER MalzemeKod2 AS CHARACTER.
DEFINE INPUT PARAMETER ReceteKod AS CHARACTER.
DEFINE INPUT PARAMETER Tip AS LOGICAL.
DEFINE INPUT PARAMETER Birim AS CHARACTER.
DEFINE INPUT PARAMETER Miktar AS DECIMAL.
DEFINE INPUT PARAMETER Aciklama AS CHARACTER.
DEFINE OUTPUT PARAMETER IslemSonucu AS CHARACTER.

{Include3\Baglanti.i}

RUN ErpReceteDegistir_run (INPUT fkod, INPUT ukod, INPUT IsEmriNo, INPUT MalzemeKod,
                           INPUT MalzemeKod2, INPUT ReceteKod, INPUT Tip, INPUT Birim, INPUT Miktar, INPUT Aciklama, OUTPUT IslemSonucu).
