
/**********************
***********************/

   DEF TEMP-TABLE Hurdalar
      FIELD HurdaId AS INTEGER
      FIELD HurdaKod AS CHARACTER FORMAT "X(32)":U 
      FIELD HurdaAd AS CHARACTER FORMAT "X(127)":U 
      FIELD HurdaAciklama AS CHARACTER FORMAT "X(127)":U
      FIELD HammaddeTuket AS LOGICAL
      FIELD BilesenHurda AS LOGICAL
      FIELD TransferYap AS LOGICAL
      FIELD HareketId AS INTEGER
      FIELD HareketKod AS CHARACTER FORMAT "X(31)":U.
      
   
DEFINE DATASET HurdalarDS FOR Hurdalar.
DEFINE OUTPUT PARAMETER DATASET FOR HurdalarDS. 

DEFINE INPUT PARAMETER  xKod AS CHARACTER.
DEFINE INPUT PARAMETER  xAd AS CHARACTER.
DEFINE INPUT PARAMETER  xAciklama AS CHARACTER.
DEFINE INPUT PARAMETER  xBilesen AS LOGICAL INITIAL FALSE.

DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}

RUN Hurdalar_run (OUTPUT TABLE Hurdalar, INPUT xKod, INPUT xAd, INPUT xAciklama, INPUT xBilesen, INPUT Firma, INPUT Limit).
