/*
Kalite kaydini bulmak icin
*/

DEFINE TEMP-TABLE V_KaliteBelgeleri
    FIELD StokKod AS CHARACTER
    FIELD StokAd AS CHARACTER
    FIELD Birim AS CHARACTER
    FIELD GMiktar AS DECIMAL
    FIELD CMiktar AS DECIMAL
    FIELD DepoKod AS CHARACTER
    FIELD OnayKod AS CHARACTER
    FIELD Durum AS CHARACTER.

DEFINE DATASET KaliteBelgeleriDS FOR V_KaliteBelgeleri.
DEFINE OUTPUT PARAMETER DATASET FOR KaliteBelgeleriDS. 

DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER  xCari AS CHARACTER.
DEFINE INPUT PARAMETER  xBelge AS CHARACTER.
DEFINE INPUT PARAMETER  xStok AS CHARACTER.
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}

RUN KaliteBelgeleri_run (
    OUTPUT TABLE V_KaliteBelgeleri, 
    INPUT Firma, INPUT xCari, INPUT xBelge, INPUT xStok, INPUT Limit).

