DEF TEMP-TABLE Malzemeler        
      FIELD  MalzemeKod AS CHARACTER FORMAT "X(32)":U 
      FIELD  MalzemeAd AS CHARACTER FORMAT "X(64)":U 
      FIELD  MalzemeAd2 AS CHARACTER FORMAT "X(64)":U 
      FIELD  Birim AS CHARACTER FORMAT "X(8)":U 
      FIELD  KdvOran AS DECIMAL
      FIELD  MinStok AS DECIMAL
      FIELD  MaxStok AS DECIMAL
      FIELD  FazlaSipOran AS DECIMAL
      FIELD  BirimId AS INTEGER
      FIELD  MalzemeId AS INTEGER
      FIELD  HammaddeTakip AS INTEGER
      FIELD  Tip AS INTEGER
      FIELD  TipKod AS CHARACTER.

DEFINE DATASET MalzemelerDS FOR Malzemeler.
DEFINE OUTPUT PARAMETER DATASET FOR MalzemelerDS. 

DEFINE INPUT PARAMETER xkod AS CHARACTER.
DEFINE INPUT PARAMETER xad AS CHARACTER.
DEFINE INPUT PARAMETER xaciklama AS CHARACTER.
DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}

RUN Malzemeler_run (OUTPUT TABLE Malzemeler, INPUT xkod, INPUT xad, INPUT xaciklama, INPUT Firma, INPUT Limit).
