DEF TEMP-TABLE Personeller
      FIELD  PersonelId AS INTEGER
      FIELD  PersonelKod AS CHARACTER FORMAT "X(32)":U
      FIELD  PersonelAdi AS CHARACTER FORMAT "X(32)":U
      FIELD  PersonelSoyad AS CHARACTER FORMAT "X(64)":U
      FIELD  DepartmanKod AS CHARACTER FORMAT "X(32)":U
      FIELD  GorevKod AS CHARACTER FORMAT "X(32)":U
      FIELD  IsyeriKod AS CHARACTER FORMAT "X(32)":U
      FIELD  Aciklama AS CHARACTER FORMAT "X(64)":U.

          
DEFINE DATASET PersonellerDS FOR Personeller.
DEFINE OUTPUT PARAMETER DATASET FOR PersonellerDS. 

DEFINE INPUT PARAMETER  xkod AS CHARACTER.
DEFINE INPUT PARAMETER  xad AS CHARACTER.
DEFINE INPUT PARAMETER  xsoyad AS CHARACTER.
DEFINE INPUT PARAMETER  xdepartman AS CHARACTER.
DEFINE INPUT PARAMETER  xgorevkod AS CHARACTER.

DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}

RUN Personeller_run (OUTPUT TABLE Personeller, INPUT xkod, INPUT xad, INPUT xsoyad, INPUT xdepartman, INPUT xgorevkod, INPUT Firma, INPUT Limit).
