/**********************
***********************/

   DEF TEMP-TABLE SevkEmriDetaylari
      FIELD SevkEmirNo AS CHARACTER FORMAT "X(32)":U  
      FIELD CariKod AS CHARACTER FORMAT "X(32)":U  
      FIELD CariAd AS CHARACTER FORMAT "X(128)":U   
      FIELD MalzemeKod AS CHARACTER FORMAT "X(32)":U  
      FIELD MalzemeAd AS CHARACTER FORMAT "X(32)":U
      FIELD CariMalzemeKod AS CHARACTER FORMAT "X(32)":U  
      FIELD Birim AS CHARACTER FORMAT "X(32)":U  
      FIELD Miktar AS DECIMAL
      FIELD Okunan AS DECIMAL  
      FIELD Kalan AS DECIMAL
      FIELD StokMiktar AS DECIMAL
      FIELD OzelKod AS CHARACTER FORMAT "X(32)":U  
      FIELD DepoKod AS CHARACTER FORMAT "X(32)":U
      FIELD SiparisNo AS CHARACTER FORMAT "X(32)":U
      FIELD SevkEmriId AS INTEGER
      FIELD SevkEmriDetayId AS INTEGER
      FIELD CariId AS INTEGER
      FIELD MalzemeId AS INTEGER
      FIELD BirimId AS INTEGER
      FIELD SiraNo AS INTEGER
      FIELD DepoId AS INTEGER
      FIELD HizmetKartId AS INTEGER
      FIELD TeslimTarih AS CHARACTER FORMAT "X(10)":U  
      FIELD Aciklama AS CHARACTER FORMAT "X(64)":U.      
   
DEFINE DATASET SevkEmriDetaylariDS FOR SevkEmriDetaylari.
DEFINE OUTPUT PARAMETER DATASET FOR SevkEmriDetaylariDS. 

DEFINE INPUT PARAMETER xSevkEmriId AS INTEGER INITIAL 0.
DEFINE INPUT PARAMETER xSevkEmriNo AS CHARACTER FORMAT "X(32)":U INITIAL "280912ÝTALYA-3".
DEFINE INPUT PARAMETER xDepoStok AS LOGICAL INITIAL FALSE.
DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}
 
RUN SevkEmriDetaylari_run (OUTPUT TABLE SevkEmriDetaylari, INPUT xSevkEmriId, INPUT xSevkEmriNo, INPUT xDepoStok, INPUT Firma, INPUT Limit).

