/**********************
***********************/

   DEF TEMP-TABLE SevkEmirleri
      FIELD SevkEmirNo AS CHARACTER FORMAT "X(32)":U  
      FIELD CariKod AS CHARACTER FORMAT "X(32)":U  
      FIELD CariAd AS CHARACTER FORMAT "X(128)":U  
      FIELD Aciklama AS CHARACTER FORMAT "X(64)":U
      FIELD SevkEmriId AS INTEGER      
      FIELD CariId AS INTEGER      
      FIELD YuklemeTarih AS CHARACTER FORMAT "X(10)":U
      FIELD CariGrup AS CHARACTER FORMAT "X(32)":U.
      
   
DEFINE DATASET SevkEmirleriDS FOR SevkEmirleri.
DEFINE OUTPUT PARAMETER DATASET FOR SevkEmirleriDS. 


DEFINE INPUT PARAMETER  xCariKod AS CHARACTER FORMAT "X(32)":U.
DEFINE INPUT PARAMETER  xCariAd AS CHARACTER FORMAT "X(32)":U.
DEFINE INPUT PARAMETER  xGrupKod AS CHARACTER FORMAT "X(32)":U.
DEFINE INPUT PARAMETER  xSevkEmirNo AS CHARACTER FORMAT "X(32)":U.
DEFINE INPUT PARAMETER  xDepogoster AS LOGICAL.


DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}

RUN SevkEmirleri_run (OUTPUT TABLE SevkEmirleri, 
                      INPUT xCariKod, INPUT xCariAd, INPUT xGrupKod, INPUT xSevkEmirNo, INPUT xDepogoster, INPUT Firma, INPUT Limit). 
