
 
 
DEF TEMP-TABLE Aletler
      FIELD  AletId  AS INTEGER 
      FIELD  AletKod  AS CHARACTER  
      FIELD  AletAd  AS CHARACTER
      FIELD  Aciklama  AS CHARACTER   
      FIELD  GrupKod  AS CHARACTER         
      FIELD  DepoKod  AS CHARACTER 
      FIELD  RafKod  AS CHARACTER
      FIELD  DemirBasKod  AS CHARACTER.

DEFINE DATASET AletlerDS FOR Aletler.
DEFINE OUTPUT PARAMETER DATASET FOR AletlerDS.
DEFINE INPUT PARAMETER  xKod AS CHAR.
DEFINE INPUT PARAMETER  xAciklama AS CHAR.

DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011" NO-UNDO.
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100 NO-UNDO.

{Include3\Baglanti.i}

RUN Aletler_run (OUTPUT TABLE Aletler, INPUT xKod, INPUT xAciklama, INPUT Firma, INPUT Limit).
