
/**********************
***********************/

   DEF TEMP-TABLE Depolar
      FIELD DepoId AS INTEGER
      FIELD DepoKod AS CHARACTER FORMAT "X(32)":U 
      FIELD DepoAd AS CHARACTER FORMAT "X(32)":U 
      FIELD Aciklama AS CHARACTER FORMAT "X(127)":U 
      FIELD Barkod AS CHARACTER FORMAT "X(127)":U
      FIELD Hurda AS LOGICAL
      FIELD Fason AS LOGICAL
      FIELD EksiStok AS LOGICAL
      FIELD HaricDepo AS LOGICAL.      
      
   
DEFINE DATASET DepolarDS FOR Depolar.
DEFINE OUTPUT PARAMETER DATASET FOR DepolarDS.

DEFINE INPUT PARAMETER  xKod AS CHARACTER.
DEFINE INPUT PARAMETER  xAd AS CHARACTER.
DEFINE INPUT PARAMETER  xAciklama AS CHARACTER.
DEFINE INPUT PARAMETER  xHurda AS LOGICAL INITIAL FALSE.

DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}

RUN Depolar_run (OUTPUT TABLE Depolar, INPUT xKod, INPUT xAd, INPUT xAciklama, INPUT xHurda, INPUT Firma, INPUT Limit).



