/*
Canavar.toro
26 Temmuz 2012 15:50 Arma filtre
*/

DEFINE TEMP-TABLE FasonGelis
    FIELD IsEmriNo AS CHARACTER FORMAT "X(60)":U
    FIELD OperasyonKod AS CHARACTER FORMAT "X(60)":U
    FIELD MalzemeKod AS CHARACTER FORMAT "X(60)":U
    FIELD PartiKod AS CHARACTER FORMAT "X(60)":U
    FIELD Miktar AS DECIMAL FORMAT "->>>,>>>,>>>,>>>,>>9.999"
    FIELD Tamamlandi AS LOGICAL.

DEFINE INPUT PARAMETER xFirmaKod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xUserKod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xDepoKod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xIstasyonKod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xBelgeTarih AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xHareketKod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xBelgeNo AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xKayitId AS INTEGER NO-UNDO.

DEFINE DATASET FasonGelisDS FOR FasonGelis.
DEFINE INPUT PARAMETER DATASET FOR FasonGelisDS. 

DEFINE OUTPUT PARAMETER MasterNo AS DECIMAL NO-UNDO.
DEFINE OUTPUT PARAMETER DetaySatir AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER IslemSonucu AS CHARACTER NO-UNDO.

{Include3\Baglanti.i}

RUN FasonDonus_run (INPUT xFirmaKod, INPUT xUserKod, INPUT xDepoKod, INPUT xIstasyonKod, 
                    INPUT xBelgeTarih, INPUT xHareketKod, INPUT xBelgeNo, INPUT xKayitId,
                    INPUT TABLE FasonGelis, OUTPUT MasterNo, OUTPUT DetaySatir, OUTPUT IslemSonucu).


DEFINE VARIABLE xfile-line AS CHARACTER INITIAL "".
INPUT FROM VALUE(SEARCH(barset-log-dir + "fasond_" + xBelgeNo + ".txt")) NO-ECHO.
  REPEAT:
  IMPORT UNFORMATTED xfile-line.
  SET IslemSonucu = IslemSonucu + xfile-line.
  END.
INPUT CLOSE.
