

DEF TEMP-TABLE xIrsaliyeDetay         
            FIELD StokKodu AS CHARACTER
            FIELD PartiNo AS CHARACTER
            FIELD Birim AS CHARACTER FORMAT "X(10)"
            FIELD Miktar AS DECIMAL
            FIELD DepoKod AS CHARACTER.


DEFINE INPUT PARAMETER FirmaKod     AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER KullaniciKod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER KayitId      AS INTEGER   NO-UNDO.
DEFINE INPUT PARAMETER BelgeNo      AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER BelgeTarih   AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER HareketKod   AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER DigerDepo    AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER CariKod      AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER Aciklama     AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER AdresKod     AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER OzelKod1     AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER OzelKod2     AS CHARACTER NO-UNDO.

DEFINE DATASET xIrsaliyeDetayDS FOR xIrsaliyeDetay.
DEFINE INPUT PARAMETER DATASET FOR xIrsaliyeDetayDS. 

DEFINE OUTPUT PARAMETER MasterNo AS INTEGER.
DEFINE OUTPUT PARAMETER DetaySatir AS INTEGER.
DEFINE OUTPUT PARAMETER IslemSonucu AS CHARACTER.

{Include3\Baglanti.i}


RUN IrsaliyeKaydi_run (INPUT FirmaKod, INPUT KullaniciKod, INPUT KayitId,
                         INPUT BelgeNo, INPUT BelgeTarih, INPUT HareketKod, 
						 INPUT DigerDepo, INPUT CariKod, INPUT Aciklama, 
						 INPUT AdresKod, INPUT OzelKod1, INPUT OzelKod2,
                         INPUT TABLE xIrsaliyeDetay, OUTPUT MasterNo, OUTPUT DetaySatir, OUTPUT IslemSonucu).


