

DEF TEMP-TABLE Raflar
    FIELD DepoId AS INTEGER
    FIELD DepoKod AS CHARACTER FORMAT "X(32)":U
    FIELD DepoAd AS CHARACTER
    FIELD RafId AS INTEGER LABEL "Raf Id" 
    FIELD RafKod AS CHARACTER FORMAT "X(32)":U
    FIELD Aciklama AS CHARACTER FORMAT "X(127)":U
    FIELD HiyerArsi AS INTEGER
    FIELD Seviye AS INTEGER
    FIELD Rapor AS LOGICAL FORMAT "1/0"
    FIELD Barkod AS CHARACTER FORMAT "X(64)":U
    FIELD Sayim AS LOGICAL FORMAT "1/0"
    FIELD EksiStok AS LOGICAL FORMAT "1/0"
    FIELD Sevkiyat AS LOGICAL FORMAT "1/0"
    FIELD IstasyonMu AS LOGICAL FORMAT "1/0"
    INDEX raf_id IS UNIQUE RafId ASCENDING.

/*DEF TEMP-TABLE Raf LIKE Raflar.*/

DEFINE DATASET RaflarDS FOR Raflar.
DEFINE OUTPUT PARAMETER DATASET FOR RaflarDS.

DEFINE INPUT PARAMETER FirmaKod AS CHARACTER.
DEFINE INPUT PARAMETER DepoId AS INTEGER INITIAL -1.
DEFINE INPUT PARAMETER DepoKod AS CHARACTER INITIAL -1.
DEFINE INPUT PARAMETER RafKod AS CHARACTER INITIAL -1.
DEFINE INPUT PARAMETER hiyer_arsi AS INTEGER INITIAL -1.
DEFINE INPUT PARAMETER limit AS INTEGER.

{Include3\Baglanti.i}

RUN Raflar_run (OUTPUT TABLE Raflar, INPUT FirmaKod, INPUT DepoId, INPUT DepoKod, INPUT RafKod, INPUT hiyer_arsi, INPUT limit).

/*FOR EACH Raf:
    CREATE Raflar.
        BUFFER-COPY Raf TO Raflar.
END.*/

