

{Include3\Baglanti.i}

DEFINE INPUT PARAMETER xFirmaKod AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xUserKod  AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xLogFile AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER xKayitId AS INTEGER NO-UNDO.
DEFINE OUTPUT PARAMETER IslemSonucu AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER DetaySatir AS INTEGER INITIAL 0 NO-UNDO.

RUN StokHareketSil_run (INPUT xFirmaKod, INPUT xUserKod, INPUT xLogFile, INPUT xKayitId,
                        OUTPUT IslemSonucu, OUTPUT DetaySatir).







