/**********************
***********************/


   DEF TEMP-TABLE V_Siparisler
      FIELD  SiparisNo  AS CHARACTER FORMAT "X(32)":U  
      FIELD  CariKod  AS CHARACTER FORMAT "X(32)":U  
      FIELD  CariAd  AS CHARACTER FORMAT "X(32)":U  
      FIELD  Aciklama  AS CHARACTER FORMAT "X(32)":U  
      FIELD  AlisSatis  AS CHARACTER FORMAT "X(8)":U  
      FIELD  DepoKodu  AS CHARACTER FORMAT "X(32)":U  
      FIELD  SiparisTarihi AS CHARACTER FORMAT "99/99/9999":U
      FIELD  SevkTarihi  AS CHARACTER FORMAT "99/99/9999":U
      FIELD  TeslimTarihi  AS CHARACTER FORMAT "99/99/9999":U
      FIELD  SiparisId  AS INTEGER
      FIELD  CariId  AS INTEGER
      FIELD  DepoId  AS INTEGER.
      
   
DEFINE DATASET SiparislerDS FOR V_Siparisler.
DEFINE OUTPUT PARAMETER DATASET FOR SiparislerDS.

DEFINE INPUT PARAMETER xId AS INTEGER.
DEFINE INPUT PARAMETER xId2 AS INTEGER.
DEFINE INPUT PARAMETER xCariKod AS CHARACTER.
DEFINE INPUT PARAMETER xCariAd AS CHARACTER.
DEFINE INPUT PARAMETER xSipNo AS CHARACTER.
DEFINE INPUT PARAMETER xAlisSatis AS CHARACTER.
DEFINE INPUT PARAMETER Firma AS CHARACTER INITIAL "ARMA2011".
DEFINE INPUT PARAMETER Limit AS INTEGER INITIAL 100.

{Include3\Baglanti.i}

RUN V_Siparisler_run (OUTPUT TABLE V_Siparisler, INPUT xCariKod, INPUT xCariAd, INPUT xSipNo, INPUT xAlisSatis, INPUT Firma, INPUT Limit).
